version: '3'

services:
  pdf-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - API_KEY=${API_KEY}
    volumes:
      - ./templates:/app/templates
    restart: always 